version: '3.8'

services:
  client:
    image: nickchaidocker/vertexai-prediction-interface-client
    build: ./client
    ports:
      - '80:3000'
    depends_on:
      - server

  server:
    image: nickchaidocker/vertexai-prediction-interface-server
    build: ./server
    ports:
      - '8080:8080'
    environment:
      - GOOGLE_SERVICE_ACCOUNT=${GOOGLE_SERVICE_ACCOUNT}
